In [ ]:
# Run if working on Google Colab
from google.colab import drive
import os

# Mount drive
drive.mount('/content/drive')

folder_path = '/content/drive/My Drive/systemic_lupus' # Change the path to the folder stored in Google Drive.

# Files in the folder -
os.listdir(folder_path)

os.chdir(folder_path)

print('Current working directory -', os.getcwd())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Current working directory - /content/drive/My Drive/systemic_lupus

In [ ]:
import pandas as pd

# Read csv file
data = pd.read_csv('data/Features/systemic lupus_Dataset_Team_ML.csv')
labels = pd.read_csv('data/Labels/Systemic_Lupus_labels.txt', delimiter='\t')

print(data.head())
print(labels.head())

        ID  Ancestry_African  Ancestry_Any other Asian background  \
0  5713894               0.0                                  0.0
1  2048882               0.0                                  0.0
2  1748132               0.0                                  0.0
3  3772083               0.0                                  0.0
4  4376107               0.0                                  0.0

   Ancestry_Any other Black background  Ancestry_Any other mixed background  \
0                                  0.0                                  0.0
1                                  0.0                                  0.0
2                                  0.0                                  0.0
3                                  0.0                                  0.0
4                                  0.0                                  0.0

   Ancestry_Any other white background  Ancestry_Asian or Asian British  \
0                                  0.0                              0.0
1                                  0.0                              0.0
2                                  0.0                              0.0
3                                  0.0                              0.0
4                                  1.0                              0.0

   Ancestry_Bangladeshi  Ancestry_Black or Black British  Ancestry_British  \
0                   0.0                              0.0               1.0
1                   0.0                              0.0               1.0
2                   0.0                              0.0               1.0
3                   0.0                              0.0               1.0
4                   0.0                              0.0               0.0

   ...  f.1558.0.0_Daily or almost daily  f.1558.0.0_Never  \
0  ...                               0.0               1.0
1  ...                               0.0               0.0
2  ...                               0.0               0.0
3  ...                               0.0               0.0
4  ...                               0.0               0.0

   f.1558.0.0_Once or twice a week  f.1558.0.0_One to three times a month  \
0                              0.0                                    0.0
1                              0.0                                    1.0
2                              0.0                                    0.0
3                              1.0                                    0.0
4                              0.0                                    0.0

   f.1558.0.0_Prefer not to answer  f.1558.0.0_Special occasions only  \
0                              0.0                                0.0
1                              0.0                                0.0
2                              0.0                                0.0
3                              0.0                                0.0
4                              0.0                                1.0

   f.1558.0.0_Three or four times a week  f.6177.0.0_Insulin  f.31.0.0_Female  \
0                                    0.0                 0.0              0.0
1                                    0.0                 0.0              1.0
2                                    1.0                 0.0              1.0
3                                    0.0                 0.0              0.0
4                                    0.0                 0.0              1.0

   f.31.0.0_Male
0            1.0
1            0.0
2            0.0
3            1.0
4            0.0

[5 rows x 56 columns]
    UKB ID  time_window_incident/nan/1.0/nan/av1  \
0  5713894                                   0.0
1  2048882                                   0.0
2  1748132                                   0.0
3  3772083                                   0.0
4  4376107                                   0.0

   time_window_incident/nan/2.0/nan/av1  time_window_incident/nan/3.0/nan/av1  \
0                                   0.0                                   0.0
1                                   0.0                                   0.0
2                                   0.0                                   0.0
3                                   0.0                                   0.0
4                                   0.0                                   0.0

   time_window_incident/nan/4.0/nan/av1  time_window_incident/nan/5.0/nan/av1  \
0                                   0.0                                   0.0
1                                   0.0                                   0.0
2                                   0.0                                   0.0
3                                   0.0                                   0.0
4                                   0.0                                   0.0

   time_window_incident/nan/6.0/nan/av1  time_window_incident/nan/7.0/nan/av1  \
0                                   0.0                                   0.0
1                                   0.0                                   0.0
2                                   0.0                                   0.0
3                                   0.0                                   0.0
4                                   0.0                                   0.0

   time_window_incident/nan/8.0/nan/av1  time_window_incident/nan/9.0/nan/av1  \
0                                   0.0                                   0.0
1                                   0.0                                   0.0
2                                   0.0                                   0.0
3                                   0.0                                   0.0
4                                   0.0                                   0.0

   time_window_incident/nan/10.0/nan/av1  all_incident/controls/nan/nan/av1  \
0                                    0.0                                0.0
1                                    0.0                                0.0
2                                    0.0                                0.0
3                                    0.0                                0.0
4                                    0.0                                0.0

   all_incident/nan/nan/nan/av1  age_range_incident/controls/50.0/60.0/av1  \
0                           0.0                                        0.0
1                           0.0                                        0.0
2                           0.0                                        0.0
3                           0.0                                        0.0
4                           0.0                                        0.0

   age_range_incident/nan/50.0/60.0/av1  all_cases/controls/nan/nan/av1  \
0                                   0.0                             0.0
1                                   0.0                             0.0
2                                   0.0                             0.0
3                                   0.0                             0.0
4                                   0.0                             0.0

   all_cases/nan/nan/nan/av1  all_cases_by_age/controls/45.0/nan/av1  \
0                        0.0                                     0.0
1                        0.0                                     0.0
2                        0.0                                     0.0
3                        0.0                                     0.0
4                        0.0                                     0.0

   all_cases_by_age/nan/45.0/nan/av1
0                                0.0
1                                0.0
2                                0.0
3                                0.0
4                                0.0

In [ ]:
# join dataset based on patient ids
# use left join to keep filtered data
data = pd.merge(data, labels[['UKB ID', 'time_window_incident/nan/10.0/nan/av1']], left_on='ID', right_on='UKB ID', how='left')
data = data.drop(columns=['UKB ID'])

In [ ]:
data = data.dropna()

In [ ]:
data.describe()

,ID,Ancestry_African,Ancestry_Any other Asian background,Ancestry_Any other Black background,Ancestry_Any other mixed background,Ancestry_Any other white background,Ancestry_Asian or Asian British,Ancestry_Bangladeshi,Ancestry_Black or Black British,Ancestry_British,...,f.1558.0.0_Never,f.1558.0.0_Once or twice a week,f.1558.0.0_One to three times a month,f.1558.0.0_Prefer not to answer,f.1558.0.0_Special occasions only,f.1558.0.0_Three or four times a week,f.6177.0.0_Insulin,f.31.0.0_Female,f.31.0.0_Male,time_window_incident/nan/10.0/nan/av1
count,4.799030e+05,479903.000000,479903.000000,479903.000000,479903.000000,479903.000000,479903.000000,479903.000000,479903.000000,479903.000000,...,479903.000000,479903.000000,479903.000000,479903.000000,479903.000000,479903.000000,479903.000000,479903.000000,479903.000000,479903.000000
mean,3.514246e+06,0.006839,0.003701,0.000252,0.002067,0.032517,0.000088,0.000469,0.000056,0.880422,...,0.079047,0.258642,0.111858,0.001154,0.114421,0.231616,0.000827,0.549788,0.450212,0.002075
std,1.451100e+06,0.082414,0.060721,0.015877,0.045418,0.177369,0.009355,0.021648,0.007501,0.324468,...,0.269813,0.437889,0.315192,0.033957,0.318322,0.421865,0.028750,0.497515,0.497515,0.045510
min,1.000028e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.257202e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.514848e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
75%,4.771166e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000
max,6.026413e+06,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
len(data.columns)

57

In [ ]:
int(data['f.904.0.0_Do not know'].sum())

21037

In [ ]:
int(data['f.904.0.0_Prefer not to answer'].sum())

3767

In [ ]:
int(data['f.20116.0.0_Prefer not to answer'].sum())

1894

In [ ]:
int(data['f.6145_Prefer not to answer'].sum())

3317

In [ ]:
int(data['f.1558.0.0_Prefer not to answer'].sum())

554

In [ ]:
data = data[data['f.904.0.0_Do not know'] == 0]
data = data[data['f.904.0.0_Prefer not to answer'] == 0]
data = data[data['f.20116.0.0_Prefer not to answer'] == 0]
data = data[data['f.6145_Prefer not to answer'] == 0]
data = data[data['f.1558.0.0_Prefer not to answer'] == 0]

In [ ]:
data.describe()

,ID,Ancestry_African,Ancestry_Any other Asian background,Ancestry_Any other Black background,Ancestry_Any other mixed background,Ancestry_Any other white background,Ancestry_Asian or Asian British,Ancestry_Bangladeshi,Ancestry_Black or Black British,Ancestry_British,...,f.1558.0.0_Never,f.1558.0.0_Once or twice a week,f.1558.0.0_One to three times a month,f.1558.0.0_Prefer not to answer,f.1558.0.0_Special occasions only,f.1558.0.0_Three or four times a week,f.6177.0.0_Insulin,f.31.0.0_Female,f.31.0.0_Male,time_window_incident/nan/10.0/nan/av1
count,4.513620e+05,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,...,451362.000000,451362.000000,451362.000000,451362.0,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000
mean,3.513976e+06,0.006077,0.003184,0.000217,0.002014,0.032874,0.000066,0.000348,0.000042,0.886461,...,0.073387,0.259481,0.112052,0.0,0.110133,0.236677,0.000780,0.546107,0.453893,0.002018
std,1.451125e+06,0.077719,0.056334,0.014733,0.044831,0.178307,0.008152,0.018647,0.006488,0.317250,...,0.260771,0.438351,0.315431,0.0,0.313056,0.425043,0.027915,0.497870,0.497870,0.044881
min,1.000028e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.256578e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.514582e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
75%,4.771098e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,1.000000,0.000000,0.0,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000
max,6.026413e+06,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
# List of columns to drop
columns_to_drop = [
    'f.904.0.0_Do not know',
    'f.904.0.0_Prefer not to answer',
    'f.20116.0.0_Prefer not to answer',
    'f.6145_Prefer not to answer',
    'f.1558.0.0_Prefer not to answer'
]

# Drop the columns
data = data.drop(columns=columns_to_drop)

In [ ]:
len(data.columns)

52

In [ ]:
# Columns related to stress events
stress_columns = [
    'f.6145_Death of a close relative',
    'f.6145_Serious illness, injury or assault to yourself',
    'f.6145_Serious illness, injury or assault of a close relative',
    'f.6145_Financial difficulties',
    'f.6145_Marital separation/divorce',
    'f.6145_Death of a spouse or partner'
]

# Creating new column 'Experienced Stress'
data['Experienced Stress'] = data[stress_columns].any(axis=1).astype(int)

# Updating 'Experienced Stress' to 0 if 'f.6145_None of the above' is 1
data.loc[data['f.6145_None of the above'] == 1, 'Experienced Stress'] = 0

# Drop the original columns related to stress and 'f.6145_None of the above'
data = data.drop(columns=stress_columns + ['f.6145_None of the above'])

In [ ]:
# Create the new 'Gender' column
data['Gender'] = data['f.31.0.0_Female']

# Drop the original columns
data = data.drop(columns=['f.31.0.0_Female', 'f.31.0.0_Male'])

In [ ]:
data = data.drop(columns=['f.1558.0.0_Never', 'f.20116.0.0_Never'])

In [ ]:
column_renames = {
    'f.21022.0.0': 'Age at Recruitment',
    'f.21001.0.0': 'BMI',
    'f.904.0.0': 'Number of days/week of vigorous physical activity 10+ minutes',
    'f.20107_Father_Bowel cancer': 'Father with Bowel Cancer',
    'f.20107_Father_Diabetes': 'Father with Diabetes',
    'f.20110_Mother_Bowel cancer': 'Mother with Bowel Cancer',
    'f.20110_Mother_Diabetes': 'Mother with Diabetes',
    'f.20116.0.0_Current': 'Current Smoker',
    'f.20116.0.0_Previous': 'Previous Smoker',
    'f.6177_Blood pressure medication': 'Blood Pressure Medication',
    'f.6177_Cholesterol lowering medication': 'Cholesterol Lowering Medication',
    'f.1558.0.0_Daily or almost daily': 'Alcohol intake frequency: Daily',
    'f.1558.0.0_Once or twice a week': 'Alcohol intake frequency: Once or twice a week',
    'f.1558.0.0_One to three times a month': 'Alcohol intake frequency: One to three times a month',
    'f.1558.0.0_Special occasions only': 'Alcohol intake frequency: Special occasions only',
    'f.1558.0.0_Three or four times a week': 'Alcohol intake frequency: Three or four times a week',
    'f.6177.0.0_Insulin': 'Insulin',
}

# rename columns
data = data.rename(columns=column_renames)

In [ ]:
data[list(column_renames.values())+['Gender', 'Experienced Stress', 'time_window_incident/nan/10.0/nan/av1']].describe()

,Age at Recruitment,BMI,Number of days/week of vigorous physical activity 10+ minutes,Father with Bowel Cancer,Father with Diabetes,Mother with Bowel Cancer,Mother with Diabetes,Current Smoker,Previous Smoker,Blood Pressure Medication,Cholesterol Lowering Medication,Alcohol intake frequency: Daily,Alcohol intake frequency: Once or twice a week,Alcohol intake frequency: One to three times a month,Alcohol intake frequency: Special occasions only,Alcohol intake frequency: Three or four times a week,Insulin,Gender,Experienced Stress,time_window_incident/nan/10.0/nan/av1
count,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000
mean,56.213387,27.326859,1.850066,0.050432,0.089779,0.046218,0.092522,0.098759,0.344657,0.104858,0.098393,0.206433,0.259481,0.112052,0.110133,0.236677,0.000780,0.546107,0.440985,0.002018
std,8.079601,4.713839,1.952924,0.218835,0.285866,0.209957,0.289762,0.298338,0.475257,0.306371,0.297846,0.404745,0.438351,0.315431,0.313056,0.425043,0.027915,0.497870,0.496506,0.044881
min,37.000000,12.120000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,50.000000,24.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,57.000000,26.680000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
75%,63.000000,29.750000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000
max,73.000000,68.410000,7.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
# Save the final data as a CSV file
data.to_csv('data/final_data.csv', index=True)

In [ ]:
Ancestry_columns = [
    'Ancestry_African',
    'Ancestry_Any other Asian background',
    'Ancestry_Any other Black background',
    'Ancestry_Any other mixed background',
    'Ancestry_Any other white background',
    'Ancestry_Asian or Asian British',
    'Ancestry_Bangladeshi',
    'Ancestry_Black or Black British',
    'Ancestry_British',
    'Ancestry_Caribbean',
    'Ancestry_Chinese',
    'Ancestry_Do not know',
    'Ancestry_Indian',
    'Ancestry_Irish',
    'Ancestry_Mixed',
    'Ancestry_Other ethnic group',
    'Ancestry_Pakistani',
    'Ancestry_Prefer not to answer',
    'Ancestry_White',
    'Ancestry_White and Asian',
    'Ancestry_White and Black African',
    'Ancestry_White and Black Caribbean'
]

In [ ]:
non_ancestry_data = data.drop(columns=Ancestry_columns)

# Describe only the non-ancestry columns
non_ancestry_data.describe()

,ID,Age at Recruitment,BMI,Number of days/week of vigorous physical activity 10+ minutes,Father with Bowel Cancer,Father with Diabetes,Mother with Bowel Cancer,Mother with Diabetes,Current Smoker,Previous Smoker,...,Cholesterol Lowering Medication,Alcohol intake frequency: Daily,Alcohol intake frequency: Once or twice a week,Alcohol intake frequency: One to three times a month,Alcohol intake frequency: Special occasions only,Alcohol intake frequency: Three or four times a week,Insulin,time_window_incident/nan/10.0/nan/av1,Experienced Stress,Gender
count,4.513620e+05,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,...,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000,451362.000000
mean,3.513976e+06,56.213387,27.326859,1.850066,0.050432,0.089779,0.046218,0.092522,0.098759,0.344657,...,0.098393,0.206433,0.259481,0.112052,0.110133,0.236677,0.000780,0.002018,0.440985,0.546107
std,1.451125e+06,8.079601,4.713839,1.952924,0.218835,0.285866,0.209957,0.289762,0.298338,0.475257,...,0.297846,0.404745,0.438351,0.315431,0.313056,0.425043,0.027915,0.044881,0.496506,0.497870
min,1.000028e+06,37.000000,12.120000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.256578e+06,50.000000,24.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.514582e+06,57.000000,26.680000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,4.771098e+06,63.000000,29.750000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
max,6.026413e+06,73.000000,68.410000,7.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000